#!/usr/bin/env python3
"""Strips `static ` off a whitelisted set of vani-generated C functions
so host_main.c (a separate translation unit) can call them directly.

vanic's --backend=c output makes every vani-defined top-level function
`static` (internal linkage) -- correct for a real build, where
everything links into one object anyway, but it means a SEPARATE host
test driver can't call fn_dharafs_append_raw etc. via a normal extern
declaration. Rather than #include the entire ~9500-line generated file
into host_main.c (which would also drag in its own trailing `int
main()`), this does a narrow, mechanical patch: for each name in
WHITELIST, drop the leading `static ` from every line starting with
`static <TYPE> fn_<name>(` -- both the forward declaration and the
definition share that exact shape, so one regex pass gets both. Also
removes the generated file's own `int main(void) { return
(int)fn_main(); }` trailing wrapper, since host_main.c supplies its
own main() and this harness never invokes the real kernel entry point
(fn_main starts networking/scheduling this harness has no interest in
exercising).

This is a deliberately minimal patch -- anything not in WHITELIST
stays static and simply isn't callable from host_main.c, which is
correct: those functions' own logic still runs (compiled into the
final object) but the harness has no test coverage for them yet.
"""
import re
import sys

WHITELIST = [
    "dharafs_check_permission",
    "dharafs_init",
    "dharafs_append_raw",
    "dharafs_append",
    "dharafs_read_raw_checked",
    "dharafs_write_raw_checked",
    "dharafs_delete_raw_checked",
    "dharafs_find_latest_block_raw",
    "dharafs_compact",
    "dirindex_max_slots",
    "dirindex_max_path_bytes",
    "dharafs_dirindex_reset",
    "dharafs_dirindex_hash",
    "dharafs_dirindex_path_matches",
    "dharafs_dirindex_find_slot",
    "dharafs_dirindex_lookup_raw",
    "dharafs_dirindex_upsert",
    "dharafs_dirindex_upsert_raw",
    "fsqueue_max_slots",
    "fsqueue_max_data_bytes",
    "fsqueue_max_path_bytes",
    "dharafs_queue_reset",
    "dharafs_queue_find_free_slot",
    "dharafs_queue_submit_write_raw",
    "dharafs_queue_submit_delete_raw",
    "dharafs_queue_submit",
    "dharafs_queue_pick_next",
    "dharafs_queue_dispatch_one",
    "dharafs_queue_pending_count",
    "dharafs_read_from_block_raw",
    "dharafs_find_block_as_of_raw",
    "snapshot_max_slots",
    "dharafs_snapshot_reset",
    "dharafs_snapshot_find_by_name_raw",
    "dharafs_snapshot_create_raw",
    "dharafs_snapshot_delete_raw",
    "dharafs_snapshot_pinned_seq_raw",
    "dharafs_snapshot_read_raw",
    "dharafs_snapshot_create",
    "dharafs_snapshot_delete",
    "dharafs_snapshot_read",
    "poly1305_read_u32_le",
    "poly1305_write_u32_le",
    "poly1305_mac",
    "poly1305_verify_constant_time",
    "bignum_mul_small_raw",
    "field25519_init",
    "field25519_get_bit",
    "field25519_add",
    "field25519_sub",
    "field25519_reduce16",
    "field25519_mul",
    "field25519_sqr",
    "field25519_invert",
    "x25519_clamp_scalar",
    "x25519_scalarmult",
    "sha512_rotr64",
    "sha512_read_u64",
    "sha512_write_u64",
    "sha512_write_u64_val",
    "sha512_read_be64",
    "sha512_write_be64",
    "sha512_k_init",
    "sha512_h_init",
    "sha512_compress",
    "sha512_hash",
    "sha512_bytes_equal",
    "bignum_shl1_raw",
    "ed25519_get_bit_lsb_first",
    "ed25519_get_bit_msb_first",
    "ed25519_scalar_mod_l_raw",
    "ed25519_scalar_add_mod_l",
    "ed25519_scalar_mul_mod_l",
    "ed25519_point_add",
    "ed25519_point_mul",
    "ed25519_point_equal",
    "ed25519_sqrt_candidate",
    "ed25519_point_compress",
    "ed25519_recover_x",
    "ed25519_point_decompress",
    "ed25519_secret_expand",
    "ed25519_secret_to_public",
    "ed25519_sign",
    "ed25519_verify",
    "ed25519_init",
    "pki_init",
    "pki_verify_raw",
    "pki_verify_file_raw",
    "pki_verify_file",
    "gf256_mul",
    "gf256_inv",
    "aes_rotl8",
    "aes_sbox",
    "aes128_key_expansion",
    "aes_add_round_key",
    "aes_sub_bytes",
    "aes_shift_rows",
    "aes_mix_columns",
    "aes128_encrypt_block",
    "aead_write_le64",
    "chacha20_poly1305_build_mac_data",
    "chacha20_poly1305_encrypt",
    "chacha20_poly1305_decrypt",
    "hkdf_extract",
    "hkdf_expand",
    "hkdf_hmac_sha256",
    "keccak_read_lane",
    "keccak_write_lane",
    "keccak_rotl64",
    "keccak_permute",
    "keccak_sponge",
    "sha3_256_hash",
    "sha3_512_hash",
    "shake128_squeeze",
    "shake256_squeeze",
    "keccak_bytes_equal",
    "keccak_init",
    "mlkem_init",
    "mlkem_buf_copy",
    "mlkem_poly_add",
    "mlkem_poly_sub",
    "mlkem_ntt",
    "mlkem_ntt_inv",
    "mlkem_multiply_ntts",
    "mlkem_byte_encode",
    "mlkem_byte_decode",
    "mlkem_compress_poly",
    "mlkem_decompress_poly",
    "mlkem_msg_to_poly",
    "mlkem_poly_to_msg",
    "mlkem_prf",
    "mlkem_xof",
    "mlkem_sample_ntt",
    "mlkem_sample_poly_cbd",
    "mlkem_g",
    "mlkem_h",
    "mlkem_j",
    "mlkem_generate_matrix",
    "mlkem_k_pke_keygen",
    "mlkem_k_pke_encrypt",
    "mlkem_k_pke_decrypt",
    "mlkem_keygen_internal",
    "mlkem_encaps_internal",
    "mlkem_decaps_internal",
    "dharafs_stat_raw",
    "dharafs_stat",
    "dharafs_read_raw",
    "dharafs_read",
    "dharafs_delete_raw",
    "dharafs_delete",
    "dharafs_rename_raw",
    "dharafs_tx_begin_raw",
    "dharafs_tx_begin_sentinel",
    "dharafs_rename_raw_checked",
    "dharafs_verified_companion_path_raw",
    "dharafs_write_verified_raw",
    "dharafs_write_verified_checked",
    "dharafs_read_verified_checked",
    "dharafs_log_rollover_threshold",
    "dharafs_log_record_max_len",
    "dharafs_log_retention_count",
    "dharafs_log_path_raw",
    "dharafs_log_header_path_raw",
    "dharafs_log_append_raw",
    "dharafs_attr_immutable",
    "dharafs_attr_append_only",
    "dharafs_attr_system",
    "dharafs_mode_is_immutable",
    "dharafs_mode_is_append_only",
    "dharafs_is_valid_append_only_write",
    "dharafs_set_attr_raw",
    "dharafs_get_attr_raw",
    "dharafs_chmod_checked",
    "dharafs_chown_checked",
    "dharafs_dirlist_seen_contains",
    "dharafs_dirlist_segment_equals",
    "dharafs_list_dir_raw",
    "dharafs_block_payload_cap",
    "dharafs_file_max_len",
    "dharafs_default_mode",
    "sha256_hash",
    "sha256_k_init",
    "sha256_bytes_equal",
    "chacha20_encrypt",
    "chacha20_bytes_equal",
    "bignum_add_raw",
    "bignum_sub_raw",
    "bignum_mul_raw",
    "bignum_cmp_raw",
    "bignum_limbs_equal",
    "bignum_set_limbs4",
    "lan9512_build_tx_header",
    "lan9512_rx_status_has_error",
    "lan9512_rx_status_frame_len",
    "hci_build_opcode",
    "hci_build_command",
    "hci_build_reset_command",
    "hci_build_le_set_scan_parameters_command",
    "hci_build_le_set_scan_enable_command",
    "hci_event_code",
    "hci_event_param_len",
    "hci_event_is_command_complete",
    "hci_cmd_complete_opcode",
    "hci_cmd_complete_status",
    "hci_build_le_create_connection_command",
    "hci_event_is_command_status",
    "hci_cmd_status_status",
    "hci_cmd_status_opcode",
    "hci_event_is_le_meta",
    "hci_le_meta_subevent_code",
    "hci_le_conn_complete_status",
    "hci_le_conn_complete_handle",
    "hci_le_conn_complete_role",
    "hci_le_conn_complete_peer_addr_type",
    "hci_le_conn_complete_peer_addr",
    "hci_acl_pb_flag_first",
    "hci_acl_bc_flag_point_to_point",
    "hci_acl_build_header",
    "hci_acl_get_handle",
    "hci_acl_get_pb_flag",
    "hci_acl_get_data_len",
    "l2cap_att_channel_id",
    "l2cap_signaling_channel_id",
    "l2cap_build_header",
    "l2cap_get_length",
    "l2cap_get_channel_id",
    "att_opcode_error_response",
    "att_opcode_exchange_mtu_request",
    "att_opcode_exchange_mtu_response",
    "att_opcode_read_request",
    "att_opcode_read_response",
    "att_opcode_write_request",
    "att_opcode_write_response",
    "att_get_opcode",
    "att_build_error_response",
    "att_error_request_opcode",
    "att_error_handle",
    "att_error_code",
    "att_build_exchange_mtu_request",
    "att_exchange_mtu_request_get_mtu",
    "att_build_exchange_mtu_response",
    "att_exchange_mtu_response_get_mtu",
    "att_build_read_request",
    "att_read_request_get_handle",
    "att_build_read_response",
    "att_read_response_get_value",
    "att_build_write_request",
    "att_write_request_get_handle",
    "att_write_request_get_value",
    "att_build_write_response",
    "buf_write_u16_le",
    "buf_read_u16_le",
    "diag_ring_physical_index",
    "att_error_invalid_handle",
    "att_error_read_not_permitted",
    "att_error_write_not_permitted",
    "att_error_invalid_pdu",
    "att_error_insufficient_authentication",
    "att_error_request_not_supported",
    "att_error_invalid_offset",
    "att_error_insufficient_authorization",
    "att_error_prepare_queue_full",
    "att_error_attribute_not_found",
    "att_error_attribute_not_long",
    "att_error_insufficient_encryption_key_size",
    "att_error_invalid_attribute_value_length",
    "att_error_unlikely_error",
    "att_error_insufficient_encryption",
    "att_error_unsupported_group_type",
    "att_error_insufficient_resources",
    "att_opcode_find_information_request",
    "att_opcode_find_information_response",
    "att_build_find_information_request",
    "att_find_information_response_get_format",
    "att_find_information_entry_size",
    "att_find_information_response_count",
    "att_find_information_response_get_handle_at",
    "att_find_information_response_get_uuid16_at",
    "att_opcode_read_by_type_request",
    "att_opcode_read_by_type_response",
    "att_build_read_by_type_request_uuid16",
    "att_read_by_type_response_get_entry_len",
    "att_read_by_type_response_count",
    "att_read_by_type_response_get_handle_at",
    "att_read_by_type_response_get_value_len",
    "att_read_by_type_response_get_value_at",
    "att_opcode_read_by_group_type_request",
    "att_opcode_read_by_group_type_response",
    "att_build_read_by_group_type_request_uuid16",
    "att_read_by_group_type_response_get_entry_len",
    "att_read_by_group_type_response_count",
    "att_read_by_group_type_response_get_start_handle_at",
    "att_read_by_group_type_response_get_end_handle_at",
    "att_read_by_group_type_response_get_value_len",
    "att_read_by_group_type_response_get_value_at",
    "gatt_uuid_primary_service",
    "gatt_uuid_secondary_service",
    "gatt_uuid_include",
    "gatt_uuid_characteristic",
    "gatt_uuid_char_extended_properties",
    "gatt_uuid_char_user_description",
    "gatt_uuid_client_char_configuration",
    "gatt_uuid_server_char_configuration",
    "gatt_uuid_char_presentation_format",
    "gatt_uuid_char_aggregate_format",
    "gatt_discover_reset",
    "att_find_information_response_get_uuid128_at",
    "uuid128_equal",
    "att_build_read_by_type_request_uuid128",
    "att_build_read_by_group_type_request_uuid128",
    "att_opcode_handle_value_notification",
    "att_opcode_handle_value_indication",
    "att_opcode_handle_value_confirmation",
    "l2cap_sig_code_connection_parameter_update_request",
    "l2cap_sig_code_connection_parameter_update_response",
    "l2cap_conn_param_update_result_accepted",
    "l2cap_conn_param_update_result_rejected",
    "att_build_handle_value_notification",
    "att_build_handle_value_indication",
    "att_handle_value_get_handle",
    "att_handle_value_get_value",
    "att_build_handle_value_confirmation",
    "l2cap_sig_get_code",
    "l2cap_sig_get_identifier",
    "l2cap_sig_get_length",
    "l2cap_conn_param_update_request_get_interval_min",
    "l2cap_conn_param_update_request_get_interval_max",
    "l2cap_conn_param_update_request_get_slave_latency",
    "l2cap_conn_param_update_request_get_timeout_multiplier",
    "l2cap_build_conn_param_update_response",
    "gatt_char_descriptor_range_end",
    "gatt_client_find_char_index_for_value_handle",
    "gatt_client_last_notify_handle",
    "gatt_server_max_value_len",
    "gatt_server_reset",
    "gatt_server_set_value_byte",
    "gatt_server_get_value_byte",
    "gatt_server_add_service",
    "gatt_server_add_characteristic",
    "gatt_server_find_index_for_handle",
    "gatt_server_handle_exchange_mtu",
    "gatt_server_handle_read_by_group_type",
    "gatt_server_handle_read_by_type",
    "gatt_server_handle_read",
    "gatt_server_handle_write",
    "gatt_server_handle_request",
    "dwc2_build_rtl_reg_read_setup",
    "dwc2_build_rtl_reg_write_setup",
    "hmac_sha256",
    "hmac_sha256_bytes_equal",
    "pbkdf2_hmac_sha256",
    "dharafs_crypto_transform_block",
    "dharafs_block_read",
    "dharafs_block_write",
    "fault_write_maybe_inject",
    "fault_irqburst_take",
    "fault_netdrop_maybe_inject",
    "filter_check_frame",
    "filter_build_test_frame",
]


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <in.c> <out.c>", file=sys.stderr)
        return 2
    with open(sys.argv[1], "r") as f:
        src = f.read()

    name_alt = "|".join(re.escape(n) for n in WHITELIST)
    pattern = re.compile(r"^static (?=\w[\w\s\*]*\bfn_(?:" + name_alt + r")\()", re.MULTILINE)
    patched, count = pattern.subn("", src)

    main_pattern = re.compile(r"\nint main\(void\) \{\n  return \(int\)fn_main\(\);\n\}\n")
    patched, main_count = main_pattern.subn("\n", patched)
    if main_count != 1:
        print(f"warning: expected exactly one trailing main() wrapper, found {main_count}", file=sys.stderr)

    with open(sys.argv[2], "w") as f:
        f.write(patched)

    print(f"unstatic'd {count} declarations/definitions across {len(WHITELIST)} whitelisted functions", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
